version: "3"
networks:
  expense:
volumes:
  mysql:     #docker volume cretae expense
services:
  mysql:
     image: venu9976/venuexpense:mysql #docker image push to docker hub and mentioend repo/images name here
     container_name: mysql # --name mysql
     volumes:
       - mysql:/var/lib/mysql #mysql storge path this is in cmd we give like -v mysql:/var/lib/mysql
  backend:
     image: venuexpense/backend:v1 #docker image push to docker hub and mentioend repo/image name here
     container_name: backend
     command: sh -c "sleep 4 && node opt/serever/index"
     depends_on:
     - mysql
  frontend:
    image: venuexpense/frontend:v1 #docker image push to docker hub and mentioend repo/image name here
    container_name: frontend
    ports:
      - 80:80
    depends_on:
     - backend
